package de.jandev.ls4apiserver.model.websocket;

public enum MessageType {
    FRIEND_IN_ACCEPT, FRIEND_IN_DENY, FRIEND_OUT, FRIEND_REMOVE, FRIEND_BLOCK, FRIEND_LIST, FRIEND_IN, FRIEND_UPDATE,
    MESSAGE_PRIVATE, MESSAGE_PRIVATE_GET,
    USER_UPDATE_MOTTO, USER_UPDATE_STATUS, USER_UPDATE_ICON, USER_UPDATE_SUMMONER_NAME, USER_LOGGED_IN_ANOTHER_LOCATION, USER_BAN,
    LOBBY_CREATE, LOBBY_INVITE, LOBBY_INVITE_REVOKE, LOBBY_ACCEPT, LOBBY_DENY, LOBBY_CHANGE_TYPE, LOBBY_LEAVE, LOBBY_KICK, LOBBY_CHAT, LOBBY_MATCHMAKING_START, LOBBY_SWITCH_TEAM,
    LOBBY_MATCHMAKING_STOP, LOBBY_UPDATE, LOBBY_MATCH_FOUND, LOBBY_MATCH_FOUND_UPDATE, LOBBY_CHAMPSELECT_ACCEPT, LOBBY_CHAMPSELECT_DENY, LOBBY_CHAMPSELECT_SUBSCRIBE,
    CHAMPSELECT_CHAT, CHAMPSELECT_SELECT_CHAMPION, CHAMPSELECT_BAN_SELECT_CHAMPION, CHAMPSELECT_BAN_LOCK_CHAMPION, CHAMPSELECT_LOCK_CHAMPION,
    CHAMPSELECT_SELECT_SPELL_1, CHAMPSELECT_SELECT_SPELL_2, CHAMPSELECT_SELECT_SKIN, CHAMPSELECT_UPDATE, CHAMPSELECT_TRADE_REQUEST,
    CHAMPSELECT_TRADE_ACCEPT, CHAMPSELECT_TRADE_DENY, CHAMPSELECT_ABANDON, CHAMPSELECT_GAME_START, KILL
}
